### PR TITLE
Add category filtering, display time and target

### PR DESCRIPTION
**Pull request by Azkellas**
Changes made:

- Add a Category filter (category = log target, e.g. my_crate::my_module)
- Display log time
    - local time (HH:MM:SS or HH:MM:SS.mmm)
    - time since start (Xh Ym Zs Mms)
- Display and highlight log target
- Disable alphabetic sorting of log entries (sort feature)
- Display in monospace to align text
- Fix doctests

See #21. I didn't necessarily intend to make a PR as-is, so the code isn't the cleanest. Still, the features are there and the code is functional.

### CODE REVIEW

**Comment by izolyomi** [comment]
@Azkellas The PR is awesome in general, thanks.
Giving it a bit of testing I've found that the logger panics on wasm32-unknown-unknown targets.
The panic is caused by adding timestamps using `std::time::SystemTime::now()` that always fails in plain WebAssembly "sandboxes" without Wasi.
Adding timestamps should be guarded in the code with something like `#[cfg(not(target_arch = "wasm32"))]`.

**Comment by Azkellas** [comment]
I didn't want to pull additionnal dependencies in this project, but I think the best would be to use [web-time](https://crates.io/crates/web-time) to work everywhere as timestamps are important whatever the platform you use. Given the recent discussion in the issue I'll do it. Good catch!

**Comment by Azkellas** [comment]
I actually ended up pulling `chrono` instead which I'm not super happy about but it gives timezone support which `SystemTime` / `web-time` didn't have. I also added a third time format with now a distinction between UTC (in rfc3339 format), Local time (with the correct timezone) and Since start.

@izolyomi can you check if the new version works on wasm?

**Comment by izolyomi** [comment]
> I actually ended up pulling `chrono` instead which I'm not super happy about but it gives timezone support which `SystemTime` / `web-time` didn't have. I also added a third time format with now a distinction between UTC (in rfc3339 format), Local time (with the correct timezone) and Since start.
> 
> @izolyomi can you check if the new version works on wasm?

Sorry, it still produces the same error using `trunk serve` and checking `localhost:8080` in any browser. My best guess is that your filter `target_family = "wasm"` is not working as expected and `target_arch = "wasm32"` should be used instead, but I'm not sure.

**Comment by izolyomi** [comment]
> I actually ended up pulling `chrono` instead which I'm not super happy about but it gives timezone support which `SystemTime` / `web-time` didn't have. I also added a third time format with now a distinction between UTC (in rfc3339 format), Local time (with the correct timezone) and Since start.
> 
> @izolyomi can you check if the new version works on wasm?

@Azkellas Taking a closer look I think there might be multiple problems:
1. You seem to have added chrono as a `dev-dependency`, isn't it needed as a normal dependency instead?
2. Feature `clock` of `chrono` seems to depend on `std` which will make Wasm targets fail. Probably you'll have to disable any use of LocalTime for Wasm builds to make it work.

**Comment by Azkellas** [comment]
Oh yeah the dev dependency is a copy paste mistake, my bad. I did it in a hurry as I had to leave, I'll test on wasm properly tomorrow. :)

**Comment by izolyomi** [comment]
> Oh yeah the dev dependency is a copy paste mistake, my bad. I did it in a hurry as I had to leave, I'll test on wasm properly tomorrow. :)

I've just played around with it a bit more.
Probably the exact place of the `cfg`-guarded dependencies within `Cargo.toml` does not matter because of the `[target...dependencies]` ending which is not too intuitive.

On my side both native and wasm works with the following config filters:

```toml
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
chrono = { version = "0.4", default-features = false, features = ["alloc", "clock"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
chrono = { version = "0.4", default-features = false, features = ["alloc", "clock", "wasmbind"] }
```

**Comment by Azkellas** [comment]
Thanks for investigating. The reason was that the feature to enable `wasm-bindgen` was `wasmbind` and not `wasm-bindgen`, my mistake. `target_family = "wasm"` worked fine, but it seems `target_arch = "wasm32"` is more idiomatic so I moved to it.

It works both in native and wasm for me now, I checked both.

**Comment by izolyomi** [comment]
> Thanks for investigating. The reason was that the feature to enable `wasm-bindgen` was `wasmbind` and not `wasm-bindgen`, my mistake. `target_family = "wasm"` worked fine, but it seems `target_arch = "wasm32"` is more idiomatic so I moved to it.
> 
> It works both in native and wasm for me now, I checked both.

Thanks for the fixes, I can confirm that your new version works on my system both in native and wasm.

**Comment by RegenJacob** [comment]
Great work on investigating @izolyomi wasm compatibility 
And of course big thanks to @Azkellas

I'll merge this PR now and upload to crates.io

I'm still a bit unhappy with the log formatting but I'll look into it when I actually got time

**Pull request merged**
