### PR TITLE
Regex and case-insensitive searching;  Scroll area expanding

### PR DESCRIPTION
**Pull request by liquidhelium**
Screenshots:
</img>
</img>
The scroll area looks like this before:
<details>
</img>
</details>
Now it's:
<details></img></details>

### CODE REVIEW

**Comment by RegenJacob** [comment]
Awesome work! I will check it out later.

**Comment by RegenJacob** [comment]
looks good but could you run `cargo fmt`. Just the window positioning sometimes gets weird but this is more an egui issue.

**Comment by liquidhelium** [comment]
Done.

**Comment by liquidhelium** [comment]
Seems that we are in different timezone😂
image

**Comment by RegenJacob** [comment]
> Seems that we are in different timezone😂
> image
> 

Yes my sleep cycle can be weird sometimes 😅

**Pull request merged**
